### ISSUE TITLE
mariadb > 10.1.1 includes galera support

### ISSUE THREAD

**Issue by hkheso** [maxadamo/galera-wizard#1]
Hello

This https://blog.mariadb.org/mariadb-10-1-1-galera-support/
"breaks" the check_vendor () in your code.

I did a dirty hack:
  yb = yum.YumBase()
    if yb.rpmdb.searchNevra(name='MariaDB-Galera-server'):
        bootstrap_cmd = "bootstrap"
        vendor = "mariadb"
    elif yb.rpmdb.searchNevra(name='MariaDB-server'):
        bootstrap_cmd = "bootstrap"
        vendor = "mariadb"
    elif yb.rpmdb.searchNevra(name='Percona-XtraDB-Cluster-full-56'):
        bootstrap_cmd = "bootstrap-pxc"
        vendor = "percona"

but this will only work correctly with MariaDB >= 10.1.1
perhaps you could make a version check into it.

**Comment by maxadamo** [comment]
Hello hkeso. 
thanks a lot for your update.... I don't have time to check this version of Galera (I'll do it soon), and therefore I'll trust what you're saying: the package name changed. 
It's not a dirty hack: my script as a whole is a dirty hack :) 
However I'll strip your code into: 
if yb.rpmdb.searchNevra(name='MariaDB-Galera-server') or yb.rpmdb.searchNevra(name='MariaDB-server'):
bootstrap_cmd = "bootstrap"
vendor = "mariadb"
